// Clicks through the full demo flow (brief section 2) and screenshots each step.
// Usage: node scripts/flow.mjs <outDir> <width>
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import { resolve } from 'node:path';
const [,, out, wArg = '1280'] = process.argv;
const w = Number(wArg);
const proxy = process.env.HTTPS_PROXY ? (() => { const u = new URL(process.env.HTTPS_PROXY); return { server: `${u.protocol}//${u.host}` }; })() : undefined;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', proxy });
const ctx = await browser.newContext({ viewport: { width: w, height: w < 500 ? 844 : 900 }, ignoreHTTPSErrors: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
let n = 0;
const shot = async (name, full = true) => {
  await page.waitForTimeout(350);
  await page.screenshot({ path: `${out}/${w}-${String(++n).padStart(2, '0')}-${name}.png`, fullPage: full });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  if (overflow > 0) errors.push(`${name}: horizontal overflow ${overflow}px`);
};
const click = (sel) => page.locator(sel).first().click();
const demo = async (label) => {
  await click('.demo-pill');
  await page.locator('.demo-panel').getByRole('radio', { name: label }).click();
  await page.waitForTimeout(300);
  if (await page.locator('.demo-panel').count()) await click('.demo-pill');
};

await page.goto('file://' + resolve('dist/local-preview.html'));
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.waitForTimeout(800);
await shot('landing');
await page.locator('.role-card').first().getByRole('link', { name: /Plan a Dispatch/ }).click();
await shot('signup');
await page.getByRole('button', { name: 'Continue' }).click();
await shot('dashboard');
await page.getByRole('button', { name: 'Create Dispatch' }).first().click();
await page.fill('#f-name', 'Chen Anniversary Dinner');
await page.fill('#f-loc', 'Rosewood Conservatory, 1400 SW Park Ave, Portland, OR');
await page.locator('.counter-val[aria-label="Guest count"]').fill('80');
await page.fill('#f-budget', '12000');
await shot('builder-basics');
await page.getByRole('button', { name: /Continue to/ }).click();
await page.locator('.vrow', { hasText: 'Bella Cucina' }).click();
await shot('builder-vendor');
await page.getByRole('button', { name: /Continue to/ }).click();
await click('.suggest-chip');
await shot('builder-food');
await page.getByRole('button', { name: /Continue to/ }).click();
await page.locator('.svc', { hasText: 'Petal & Stem' }).click();
await page.getByRole('button', { name: /Continue to/ }).click();
await click('.suggest-chip');
await shot('builder-staff');
await page.getByRole('button', { name: /Continue to/ }).click();
await page.getByRole('switch', { name: 'Collect RSVPs' }).click();
await page.fill('#g-name', 'Lucy Chen');
await page.fill('#g-email', 'lucy.chen@example.com');
await page.getByRole('button', { name: 'Add guest' }).click();
await shot('builder-rsvp');
await page.getByRole('button', { name: /Continue to/ }).click();
for (const m of ['Tables', 'Linens', 'Glassware']) await page.locator('.check', { hasText: m }).click();
await shot('builder-materials');
await page.getByRole('button', { name: /Continue to/ }).click();
await shot('builder-review');
await page.getByRole('button', { name: /Approve quote/ }).click();
await shot('checkout');
await page.getByRole('button', { name: /Pay \$/ }).click();
await page.waitForTimeout(1600);
await shot('confirmed');
await page.getByRole('link', { name: /Open the Dispatch Ticket/ }).click();
await shot('ticket');
await page.locator('.tk-stub').getByRole('button', { name: 'Share' }).click();
await page.fill('#share-q', 'grace');
await page.waitForTimeout(200);
await click('.result');
await page.getByRole('button', { name: 'Invite' }).click();
await shot('share', false);
await page.keyboard.press('Escape');
await demo('Vendor');
await shot('ticket-vendor');
await page.locator('.card', { hasText: 'Event basics' }).getByRole('link', { name: /Suggest edit/ }).click();
await page.locator('.counter-val[aria-label="Guest count"]').fill('70');
await shot('vendor-suggest');
await page.getByRole('button', { name: 'Send suggestion' }).click();
await demo('Client');
await shot('ticket-suggestion');
await page.locator('.sugg').getByRole('button', { name: 'Accept' }).click();
await page.getByRole('tab', { name: 'Activity' }).click();
await shot('ticket-activity');
await demo('Staff');
await shot('staff');
await page.locator('.sm-check .check').first().click();
await page.getByRole('button', { name: "I'm on my way" }).click();
await page.getByRole('button', { name: "I've arrived" }).click();
await shot('staff-arrived');
await demo('Client');
await page.getByRole('tab', { name: 'Staff' }).click();
await shot('ticket-staff');
await page.getByRole('tab', { name: 'Documents' }).click();
await page.getByRole('link', { name: /Staff Instruction Sheet/ }).click();
await shot('sheet');
await page.evaluate(() => { location.hash = '#/compare'; });
await shot('compare');
await page.evaluate(() => { location.hash = '#/dashboard'; });
await click('.demo-pill');
await page.locator('.demo-panel').getByRole('button', { name: 'About' }).click();
await shot('about', false);
await page.keyboard.press('Escape');
await click('.demo-pill');
await page.locator('.demo-panel').getByRole('button', { name: 'Empty state' }).click();
await shot('empty');
await browser.close();
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : `flow ok (${n} screenshots)`);
